### ISSUE TITLE
Потапов Артём ТКИ-342

### ISSUE THREAD

**Issue by Gladiaturuss** [Gladiaturuss/Sharp_S#1]
Потапов Артём ТКИ-342

**Comment by FlashAnton** [comment]
Здравствуйте!

Разместил в репозитории учебные материалы.

Закрепляю за Вами Вариант ~~№2~~ (№1 при условии, если с Савиным) на семестр.

Просьба подключить к данному репозиторию Вашего напарника по бригаде
и сообщить мне его Ф.И.О.

Спасибо.

**Comment by FlashAnton** [comment]
Если вместе с Савиным, тогда вариант №1.
Определитесь в чьём репозитории будем работать - в Вашем или в его.

Учебные материалы буду обновлять каждому, а работы должны храниться у кого-то одного из вас.

**Comment by Gladiaturuss** [comment]
> Если вместе с Савиным, тогда вариант №1. Определитесь в чьём репозитории будем работать - в Вашем или в его.
> 
> Учебные материалы буду обновлять каждому, а работы должны храниться у кого-то одного из вас.

Мы со Львом решили работать в моём репозитории.

**Comment by FlashAnton** [comment]
> > Если вместе с Савиным, тогда вариант №1. Определитесь в чьём репозитории будем работать - в Вашем или в его.
> > Учебные материалы буду обновлять каждому, а работы должны храниться у кого-то одного из вас.
> 
> Мы со Львом решили работать в моём репозитории.

Принято. По готовности и размещении результатов работы в репозитории оставьте здесь соответствующий комментарий, либо создайте "Pull Request" (по желанию), чтобы обратить моё внимание на изменение состава файлов в репозитории.

**Comment by Gladiaturuss** [comment]
> > > Если вместе с Савиным, тогда вариант №1. Определитесь в чьём репозитории будем работать - в Вашем или в его.
> > > Учебные материалы буду обновлять каждому, а работы должны храниться у кого-то одного из вас.
> > 
> > 
> > Мы со Львом решили работать в моём репозитории.
> 
> Принято. По готовности и размещении результатов работы в репозитории оставьте здесь соответствующий комментарий, либо создайте "Pull Request" (по желанию), чтобы обратить моё внимание на изменение состава файлов в репозитории.

Добавил файл с выполненной 1 работой.

**Comment by FlashAnton** [comment]
Корректное выполнение работы подтверждаю.

**Зачтено**
