### ISSUE TITLE
Курсовая работа

### ISSUE THREAD

**Issue by FlashAnton** [Gladiaturuss/Sharp_S#7]
Обратите, пожалуйста, внимание, что в Учебных материалах появился раздел "Курсовая работа".

"Рабочее задание. Типовая схема" - то, что необходимо реализовать.
"Структура" - разделы отчётного документа Word по курсовой работе.

В каталоге с расписаниями Excel в текстовом файле прописаны пункты,
которые необходимо отразить на Chart-элементе.

"Рабочее задание. Индивидуальная схема" - если после ознакомления с этим рабочим задания возникнут определённые мысли по какой-либо разработке, то я открыт для обсуждения и типовую схему можно будет заменить на индивидуальную.

**Данная ветвь предназначена для обсуждения всех вопросов по Курсовой работе**

**Comment by Blemtoze** [comment]
Добавлен отчёт по курсовой работе, в течение часа будет добавлен код программы.

**Comment by Blemtoze** [comment]
Добавлены файлы исходного кода курсовой работы.

**Comment by FlashAnton** [comment]
To @Blemtoze: 

Лев, извините, немного сломал Ваше авторское оформление...

Постарался починить и во многих случаях, кажется, получилось, но не везде.
Но обойдёмся без дополнительных правок. Принимаем имеющуюся версию с
"++"-ми за финальную.

Есть, безусловно, к чему в ней ещё стремиться, но реализованное Вами меня устраивает
и даже устраивает на оценку "отлично". Но только потому, что это Вы и я
знаю, как Вы работаете. В этой связи я позволил себе исключить Артёма с титульного листа,
поскольку к нему у меня есть дополнительные вопросы и пожелания.

У Вас по дисциплине "Методы программирования" - **зачёт**.
За Курсовую работу - **отлично**.

Для Артёма составлю отдельный комментарий.

**Comment by FlashAnton** [comment]
To @Gladiaturuss:

Артём, я обещал не устраивать защиту лабораторных работ, но
про Курсовую работу я этого не говорил. Мне Важно проверить
уровень приобретённых Вами знаний. На сегодня я не могу Вас
положительно оценить.

Попрошу Вас к ближайшему лабораторному занятию сделать распечатку
отчёта по Курсовой работе, подготовленного Вами совместно со Львом
и мы письменно обсудим все модификации, которые необходимо выполнить
в программном обеспечении, а также в тексте отчётного документа.

**Comment by FlashAnton** [comment]
**Отметки выполнения на "отлично" @Blemtoze и @Gladiaturuss от 14.05.2024 и 22.05.2024, соответственно**
